// <auto-generated />
using System;
using Leave_Management_System.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leave_Management_System.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContextEFCore))]
    partial class ApplicationDbContextEFCoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Leave_Management_System.Models.Domain.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = ".NET",
                            Description = "Development team working on .NET applications and services."
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Python",
                            Description = "Development team responsible for Python-based applications and APIs."
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "React",
                            Description = "Frontend development team using React.js."
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Angular",
                            Description = "Frontend development team using Angular framework."
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "React Native",
                            Description = "Mobile application development team using React Native."
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "QA",
                            Description = "Quality Assurance team responsible for testing and quality control."
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "DevOps",
                            Description = "Infrastructure, CI/CD, cloud deployment, and automation team."
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentName = "PHP",
                            Description = "Development team responsible for PHP-based web applications."
                        });
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.Holidays", b =>
                {
                    b.Property<int>("HolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.HasKey("HolidayId");

                    b.ToTable("Holidays");

                    b.HasData(
                        new
                        {
                            HolidayId = 1,
                            Description = "Harvest festival celebrated across India.",
                            HolidayDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Makar Sankranti",
                            IsOptional = false
                        },
                        new
                        {
                            HolidayId = 2,
                            Description = "Festival dedicated to Lord Shiva.",
                            HolidayDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Maha Shivratri",
                            IsOptional = false
                        },
                        new
                        {
                            HolidayId = 3,
                            Description = "Bonfire marking the victory of good over evil.",
                            HolidayDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Holika Dahan",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 4,
                            Description = "Festival of Colors.",
                            HolidayDate = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Holi (Dhulandi)",
                            IsOptional = false
                        },
                        new
                        {
                            HolidayId = 5,
                            Description = "Birth anniversary of Lord Rama.",
                            HolidayDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ram Navami",
                            IsOptional = false
                        },
                        new
                        {
                            HolidayId = 6,
                            Description = "Birth anniversary of Lord Hanuman.",
                            HolidayDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Hanuman Jayanti",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 7,
                            Description = "Auspicious day for prosperity and new beginnings.",
                            HolidayDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Akshaya Tritiya",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 8,
                            Description = "Festival honoring spiritual and academic teachers.",
                            HolidayDate = new DateTime(2026, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Guru Purnima",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 9,
                            Description = "Celebration of the bond between brothers and sisters.",
                            HolidayDate = new DateTime(2026, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Raksha Bandhan",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 10,
                            Description = "Birth anniversary of Lord Krishna.",
                            HolidayDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Janmashtami",
                            IsOptional = false
                        },
                        new
                        {
                            HolidayId = 11,
                            Description = "Birth of Lord Ganesha.",
                            HolidayDate = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Ganesh Chaturthi",
                            IsOptional = false
                        },
                        new
                        {
                            HolidayId = 12,
                            Description = "Beginning of the nine-day festival dedicated to Goddess Durga.",
                            HolidayDate = new DateTime(2026, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Sharad Navratri Begins",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 13,
                            Description = "Important day during Navratri.",
                            HolidayDate = new DateTime(2026, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Durga Ashtami",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 14,
                            Description = "Victory of Lord Rama over Ravana.",
                            HolidayDate = new DateTime(2026, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Dussehra (Vijayadashami)",
                            IsOptional = false
                        },
                        new
                        {
                            HolidayId = 15,
                            Description = "Festival observed by married Hindu women.",
                            HolidayDate = new DateTime(2026, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Karva Chauth",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 16,
                            Description = "Beginning of the Diwali festivities.",
                            HolidayDate = new DateTime(2026, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Dhanteras",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 17,
                            Description = "Also known as Choti Diwali.",
                            HolidayDate = new DateTime(2026, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Naraka Chaturdashi",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 18,
                            Description = "Festival of Lights.",
                            HolidayDate = new DateTime(2026, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Diwali (Lakshmi Puja)",
                            IsOptional = false
                        },
                        new
                        {
                            HolidayId = 19,
                            Description = "Celebration of Lord Krishna lifting Govardhan Hill.",
                            HolidayDate = new DateTime(2026, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Govardhan Puja",
                            IsOptional = true
                        },
                        new
                        {
                            HolidayId = 20,
                            Description = "Celebration of the bond between brothers and sisters.",
                            HolidayDate = new DateTime(2026, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HolidayName = "Bhai Dooj",
                            IsOptional = true
                        });
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.LeaveBalance", b =>
                {
                    b.Property<int>("LeaveBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveBalanceId"));

                    b.Property<int>("AllocatedDays")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTyprId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveYear")
                        .HasColumnType("int");

                    b.Property<int>("UsedDays")
                        .HasColumnType("int");

                    b.HasKey("LeaveBalanceId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.LeaveRequest", b =>
                {
                    b.Property<Guid>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ApproveDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeaveReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeaveStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LeaveId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.LeaveType", b =>
                {
                    b.Property<int>("LeaveTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveTypeId"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxDaysPerYear")
                        .HasColumnType("int");

                    b.HasKey("LeaveTypeId");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            LeaveTypeId = 1,
                            IsPaid = true,
                            LeaveTypeName = "Sick Leave",
                            MaxDaysPerYear = 6
                        },
                        new
                        {
                            LeaveTypeId = 2,
                            IsPaid = true,
                            LeaveTypeName = "Employee Leave (EL)",
                            MaxDaysPerYear = 12
                        },
                        new
                        {
                            LeaveTypeId = 3,
                            IsPaid = true,
                            LeaveTypeName = "Flexible Festival Leave (FFL)",
                            MaxDaysPerYear = 1
                        },
                        new
                        {
                            LeaveTypeId = 4,
                            IsPaid = true,
                            LeaveTypeName = "Management Leave (ML)",
                            MaxDaysPerYear = 3
                        });
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "HR"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.Employee", b =>
                {
                    b.HasOne("Leave_Management_System.Models.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leave_Management_System.Models.Domain.Employee", "Manager")
                        .WithMany("Employees")
                        .HasForeignKey("ManagerId");

                    b.HasOne("Leave_Management_System.Models.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.LeaveBalance", b =>
                {
                    b.HasOne("Leave_Management_System.Models.Domain.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Leave_Management_System.Models.Domain.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.LeaveRequest", b =>
                {
                    b.HasOne("Leave_Management_System.Models.Domain.Employee", "Approval")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Leave_Management_System.Models.Domain.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Leave_Management_System.Models.Domain.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approval");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Leave_Management_System.Models.Domain.Employee", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
