<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Employees\IRepository\**" />
    <EmbeddedResource Remove="Employees\IRepository\**" />
    <None Remove="Employees\IRepository\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Leave_Management_System.Data\Leave_Management_System.Data.csproj" />
    <ProjectReference Include="..\Leave_Management_System.Models\Leave_Management_System.Models.csproj" />
  </ItemGroup>

</Project>
